Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace ContactPro.Models
{
    public class Category
    {
        public int Id { get; set; }


        [Required]
        [Display(Name = "Category Name")]
        public string? Name { get; set; }


        [Required]

        public string? AppUserId { get; set; }

        // Navigation Properties

        public virtual AppUser? AppUser { get; set; }

        public virtual ICollection<Contact> Contacts { get; set; } = new HashSet<Contact>();
    }
}

Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ContactPro.Data;
using ContactPro.Models;
using ContactPro.Enums;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using ContactPro.Services.Interfaces;
using Microsoft.AspNetCore.Identity.UI.Services;

namespace ContactPro.Controllers
{

    [Authorize]
    public class CategoriesController : Controller

     






    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly IImageService _imageService;
        private readonly IEmailSender _emailService;

        public CategoriesController(ApplicationDbContext context, UserManager<AppUser> userManager, IImageService imageService, IEmailSender emailService)
        {
            _context = context;
            _userManager = userManager;
            _imageService = imageService;
            _emailService = emailService;
        }

        // GET: Categories
        public async Task<IActionResult> Index(string? swalMessage = null)


        {

            ViewData["SwalMessage"] = swalMessage;
            string userId = _userManager.GetUserId(User)!;

            

            IEnumerable<Category> categories = await _context.Categories.Where(c => c.AppUserId == userId).Include(c => c.Contacts).ThenInclude(c => c.AppUser).ToListAsync();

            return View(categories);
        }



        //GET EmailCategory

        public async Task<IActionResult> EmailCategory(int? id)
        {

            if(id == null)
            {
                return NotFound();
            }

            

            string? userId = _userManager.GetUserId(User);
            Category? category = await _context.Categories.Include(c => c.Contacts).FirstOrDefaultAsync(c => c.Id == id && c.AppUserId == userId);


            if(category == null)
            {
                return NotFound();
            }


            List<string> emails = category!.Contacts.Select(c => c.Email).ToList()!;

            EmailData emailData = new EmailData()
            {

                GroupName = category.Name,
                EmailAddress = string.Join(";", emails),
                EmailSubject = $"Group Message: {category.Name}"

            };

            return View(emailData);

        }






        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EmailCategory(EmailData emailData)
        {
            if(ModelState.IsValid)
            {
                string? swalMessage = string.Empty;
               

                try
                {
                    await _emailService.SendEmailAsync(emailData!.EmailAddress!,
                                                       emailData.EmailSubject!,
                                                      emailData.EmailBody!);


                    swalMessage = "Success: Email Sent!";


                    return RedirectToAction(nameof(Index), new { swalMessage });
                }
                catch (Exception)
                {

                    ;
                    swalMessage = "Error: Email Send Failed";
                    return RedirectToAction(nameof(Index), new { swalMessage });
                    throw;
                }

            }

            return View(emailData);
        }



        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .Include(c => c.AppUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            //ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,AppUserId")] Category category)
        {

            ModelState.Remove("AppUserId");
            if (ModelState.IsValid)
            {

                category.AppUserId = _userManager.GetUserId(User);
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", category.AppUserId);
            return View(category);


    }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            //ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", category.AppUserId);
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,AppUserId")] Category category)
        {


      
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", category.AppUserId);
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .Include(c => c.Contacts)
                .ThenInclude(c => c.AppUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Categories/Create.cshtml
@model ContactPro.Models.Category

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
@*            <div class="form-group">
                <label asp-for="AppUserId" class="control-label"></label>
                <select asp-for="AppUserId" class ="form-control" asp-items="ViewBag.AppUserId"></select>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Categories/Delete.cshtml
@model ContactPro.Models.Category
@using ContactPro.Services.Interfaces;
@inject IImageService _ImageService
@{
    ViewData["Title"] = "Delete";
}

<div class="row justify-content-center">
    <div class="col-md-8">
        <h3>Are you sure?</h3>
        <p class="text-lead text-muted">This category will be permanently deleted.</p>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-title">
                    <h3>@Model.Name</h3>
                </div>
                <div class="text-muted fs-6">
                    There @(Model.Contacts.Count == 1 ? "is 1 contact" : $"are {Model.Contacts.Count} contacts")
                    in this category
                </div>
                <div class="d-flex">
                    @foreach (Contact contact in Model.Contacts)
                    {
                        <div class="square-img-container m-2" style="height: 60px; width: 60px;"
                         data-bs-toggle="tooltip" data-bs-title="@contact.FullName" data-bs-placement="bottom">
                            <img class="square-img" src="@_ImageService.ConvertByteArrayToFile(contact.ImageDate!, contact.ImageType!)">
                        </div>
                    }
                </div>
            </div>
        </div>
        <form asp-action="Delete" class="d-flex justify-content-between pt-3">
            <input type="hidden" asp-for="Id" />
            <a asp-action="Index" class="btn btn-outline-secondary rounded-pill btnLink">Cancel</a>
            <input type="submit" value="Delete" class="btn btn-danger rounded-pill btnLink" />
        </form>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(() => {
            const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
            const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
        })
    </script>
}

Views/Categories/Details.cshtml
@model ContactPro.Models.Category

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppUser.Id)
        </dd>*@
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Categories/Edit.cshtml
@model ContactPro.Models.Category

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="AppUserId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
@*            <div class="form-group">
                <label asp-for="AppUserId" class="control-label"></label>
                <select asp-for="AppUserId" class="form-control" asp-items="ViewBag.AppUserId"></select>
                <span asp-validation-for="AppUserId" class="text-danger"></span>
            </div>*@
            <div class="my-3 form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Categories/EmailCategory.cshtml
@model ContactPro.Models.EmailData

<h1 class="mt-5">Email Category: @Model.GroupName</h1>
<div class="p-2">
    <form asp-action="EmailCategory" asp-controller="Categories" method="post">
        <input type="hidden" asp-for="@Model.GroupName" />
        <div class="row row-cols-1 row-cols-md-2 g-3 mb-3">
            <div class="col col-md-12">
                <label asp-for="@Model.EmailAddress" class="form-label">To:</label>
                <textarea type="email" readonly class="form-control" asp-for="@Model.EmailAddress" rows="3"></textarea>
            </div>
        </div>
        <div class="row row-cols-1 g-3">
            <div class="col">
                <label asp-for="@Model.EmailSubject" class="form-label">Subject:</label>
                <input type="text" class="form-control" asp-for="@Model.EmailSubject" />
            </div>
            <div class="col">
                <label asp-for="@Model.EmailBody" class="form-label">Message:</label>
                <textarea class="form-control" rows=10 asp-for="@Model.EmailBody" required></textarea>
            </div>
            <div class="col text-end">
                <button class="btn btn-primary rounded-pill btnlinks" type="submit">Send</button>
            </div>
        </div>
    </form>
</div>

Views/Categories/Index.cshtml
@using ContactPro.Services.Interfaces;
@model IEnumerable<ContactPro.Models.Category>
@inject IImageService _ImageService

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

@foreach (var item in Model)
{
    <div class="card my-3">
        <div class="card-body">
            <div class="card-title">
                <h3>@item.Name</h3>
            </div>
            <div class="text-muted fs-6">
                There @(item.Contacts.Count == 1 ? "is 1 contact" : $"are {item.Contacts.Count} contacts")
                in this category
            </div>
            <div class="d-flex">
                @foreach (Contact contact in item.Contacts)
                {
                    <div class="square-img-container m-2" style="height: 60px; width: 60px;"
                 data-bs-toggle="tooltip" data-bs-title="@contact.FullName" data-bs-placement="bottom">
                        <img class="square-img" src="@_ImageService.ConvertByteArrayToFile(contact.ImageDate!, contact.ImageType!)">
                    </div>
                }
            </div>
            <div class="d-flex justify-content-end">

                <a class="mx-3 btn btn-outline-info" asp-action="Edit" asp-route-id="@item.Id">
                    <i class="fs-3 bi bi-pencil-square"></i>
                </a>

                <a class="mx-3 btn btn-outline-secondary" asp-action="Details" asp-route-id="@item.Id">
                    <i class="fs-3 bi bi-newspaper"></i>
                </a>

                <a class="mx-3 btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">
                    <i class="fs-3 bi bi-trash"></i>
                </a>

            </div>
        </div>
    </div>
}


@section scripts {

    <script>
        let message = '@(ViewBag.SwalMessage)';

        if (!message.includes("Error") && message != '') {

            Swal.fire({
                backdrop: false,
                icon: 'success',
                title: message,
                showConfirmButton: true
            });

        } else if (message.includes('Error')) {

            Swal.fire({
                backdrop: false,
                icon: 'error',
                title: 'Oops !',
                text: message
            });


        }
    </script>
}