Models/Contact.cs
using ContactPro.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContactPro.Models
{
    public class Contact
    {

        public int Id { get; set; }

        [Required]
        public string? AppUserId { get; set; }  

        [Required]
        [Display(Name = "First Name")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and max {1} characters long.", MinimumLength = 2)]
        public string? FirstName { get; set; }


        [Required]
        [Display(Name = "Last Name")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and max {1} characters long.", MinimumLength = 2)]
        public string? LastName { get; set; }

        [NotMapped]
        public string? FullName { get { return $"{FirstName} {LastName}"; } }



        [Display(Name = "Birthday")]
        [DataType(DataType.Date)]
        public DateTime? BirthDate { get; set; }


        [Required]
        [Display(Name = "Address")]
        public string? Address1 { get; set; }


        [Display(Name = "Address 2")]
        public string? Address2 { get; set; }

        [Required]
        public string? City { get; set; }

        [Required]
        public States State { get; set; }

        [Display(Name = "Zip Code")]
        [DataType(DataType.PostalCode)]
        public int ZipCode { get; set; }


        [Required]
        [EmailAddress]
        public string? Email { get; set; }


        [Required]
        [Display(Name = "Phone Number")]
        public string? PhoneNumber { get; set; }


        [Required]
        [DataType(DataType.Date)]
        public DateTime Created { get; set; }

        public byte[]? ImageDate { get; set; }
        public string? ImageType { get; set; }

        [NotMapped]
        public IFormFile? ImageFile { get; set; }   


        //Navigation properties
        public virtual AppUser? AppUser { get; set; }

        public virtual ICollection<Category> Categories { get; set; }  = new HashSet<Category>();

    }
}

Models/ViewModels/EmailContactViewModel.cs
namespace ContactPro.Models.ViewModels
{
    public class EmailContactViewModel
    {

        public Contact? Contact { get; set; }   


        public EmailData? EmailData { get; set; }


    }
}

Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ContactPro.Data;
using ContactPro.Models;
using ContactPro.Enums;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using ContactPro.Services.Interfaces;
using ContactPro.Models.ViewModels;
using Microsoft.AspNetCore.Identity.UI.Services;
namespace ContactPro.Controllers
{
    [Authorize]
    public class ContactsController : Controller
    {
        
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly IImageService _imageService;
        private readonly IContactProService _contactProService;
        private readonly IEmailSender _emailService;


        public ContactsController(ApplicationDbContext context, UserManager<AppUser> userManager, IImageService imageService, IContactProService contactProService, IEmailSender emailService)
        {
            _context = context;
            _userManager = userManager;
            _imageService = imageService;   
            _contactProService = contactProService;
            _emailService = emailService;
        }

        // GET: Contacts
        [Authorize]
        public async Task<IActionResult> Index(int? categoryId, string? swalMessage = null)


        {


            ViewData["swalMessage"] = swalMessage;

            string? userId = _userManager.GetUserId(User)!;

            List<Contact> contacts = new List<Contact>();

            List<Category> categories = await _context.Categories.Where(c => c.AppUserId == userId).ToListAsync();


            if(categoryId == null)
            {

                contacts = await _context.Contacts.Where(c => c.AppUserId == userId).Include(c => c.Categories).ToListAsync();


            } else
            {
                contacts = (await _context.Categories.Include(c => c.Contacts).FirstOrDefaultAsync(c => c.AppUserId == userId && c.Id == categoryId))!.Contacts.ToList();
            }

          IEnumerable<Contact>  model = await _context.Contacts.Where(c => c.AppUserId == userId).Include(c => c.Categories).ToListAsync();

            ViewData["CategoryId"] = new SelectList(categories, "Id", "Name", categoryId);


            return View(contacts);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> SearchContacts(string? searchString)
        {
            string? userId = _userManager.GetUserId(User);
            List<Contact> contacts = new List<Contact>();

            AppUser? appUser = await _context.Users
                .Include(u => u.Contacts)
                .ThenInclude(c => c.Categories)
                .FirstOrDefaultAsync(u => u.Id == userId);

            if (string.IsNullOrEmpty(searchString))
            {
                contacts = appUser!.Contacts
                    .OrderBy(c => c.LastName)
                    .ThenBy(c => c.FirstName)
                    .ToList();
            } else
            {
                contacts = appUser!.Contacts
                    .Where(c => c.FullName!
                    .ToLower().Contains(searchString
                    .ToLower())).OrderBy(c => c.LastName)
                    .ThenBy(c => c.FirstName)
                    .ToList();
            }


            ViewData["CategoryId"] = new SelectList(appUser.Categories, "Id", "Name");

            return View(nameof(Index), contacts);

        }

        public async Task<IActionResult> EmailContact(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }



            


            string? userId = _userManager.GetUserId(User);

           Contact? contact = await _context.Contacts
                .FirstOrDefaultAsync(c => c.Id == id && c.AppUserId == userId);


            if(contact == null)
            {

                return NotFound();
            }


            EmailData emailData = new EmailData()
            {

                EmailAddress = contact!.Email,
                FirstName = contact.FirstName,
                LastName = contact.LastName
            };


            EmailContactViewModel viewModel = new EmailContactViewModel()
            {
                Contact = contact,
                EmailData = emailData
            };

            return View(viewModel);
        }


        // Instaniate EmailDat
            //Intaniate the ViewModel


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EmailContact(EmailContactViewModel viewModel)
        {

            if(ModelState.IsValid)
            {


                string? swalMessage = string.Empty;

                try
                {
                    await _emailService.SendEmailAsync(viewModel.EmailData!.EmailAddress!,
                                                        viewModel.EmailData.EmailSubject!,
                                                        viewModel.EmailData.EmailBody!);


                    swalMessage = "Success: Email Sent!";


                    return RedirectToAction(nameof(Index), new { swalMessage });
                }
                catch (Exception)
                {

;
                    swalMessage = "Error: Email Send Failed";
                    return RedirectToAction(nameof(Index), new { swalMessage });
                    throw;
                }
            }

            return View(viewModel);


        }




        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Contacts == null)
            {
                return NotFound();
            }

            var contact = await _context.Contacts
                .Include(c => c.AppUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // GET: Contacts/Create

        [Authorize] 
        public async Task<IActionResult> Create()
        {
            //ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id");



            //Query and present list of categories for the logged in user

            string? userId = _userManager.GetUserId(User);

            IEnumerable<Category> categoriesList = await _context.Categories
                .Where(c => c.AppUserId == userId)
                .ToListAsync();

            ViewData["CategoryList"] = new MultiSelectList(categoriesList, "Id", "Name");




            ViewData["StatesList"] = new SelectList(Enum.GetValues(typeof(States)).Cast<States>());



            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,AppUserId,FirstName,LastName,BirthDate,Address1,Address2,City,State,ZipCode,Email,PhoneNumber,Created,ImageFile")] Contact contact, IEnumerable<int> selected)
        {


            ModelState.Remove("AppUserId");

            if (ModelState.IsValid)
            {
                contact.AppUserId = _userManager.GetUserId(User);

                if(contact.ImageFile != null)
                {
                    contact.ImageDate = await _imageService.ConvertFileToByteArrayAsync(contact.ImageFile);
                    contact.ImageType = contact.ImageFile.ContentType;
                }

                if(contact.BirthDate != null)
                {
                    contact.BirthDate = DateTime.SpecifyKind(contact.BirthDate.Value, DateTimeKind.Utc);
                }
               

                contact.Created = DateTime.UtcNow;
                _context.Add(contact);
                await _context.SaveChangesAsync();

                //TODO: Add service call

                await _contactProService.AddContactToCategoriesAsync(selected, contact.Id);


                return RedirectToAction(nameof(Index));
            }
            ViewData["StatesList"] = new SelectList(Enum.GetValues(typeof(States)).Cast<States>());
            return View(contact);
        }

        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Contacts == null)
            {
                return NotFound();
            }

            var contact = await _context.Contacts
                .Include(c => c.Categories)
                .FirstOrDefaultAsync(c => c.Id == id);
    



            string? userId = _userManager.GetUserId(User);

            IEnumerable<Category> categoriesList = await _context.Categories
                .Where(c => c.AppUserId == userId)
                .ToListAsync();


            IEnumerable<int> currentCategories =  contact!.Categories.Select(c => c.Id);

            ViewData["CategoryList"] = new MultiSelectList(categoriesList, "Id", "Name", currentCategories);

            if (contact == null)
            {
                return NotFound();
            }


            ViewData["StatesList"] = new SelectList(Enum.GetValues(typeof(States)).Cast<States>());

            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

Views/Contacts/Create.cshtml
@model ContactPro.Models.Contact

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Contact</h4>
<hr />
<h1>CREATE CONTACT</h1>
<div class="p-3 border border-2 shadow-lg bg-light">
</div>
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row g-3 p-2">
                <div class="col-12 col-lg-4">
                    <div class="square-img-container">
                        <img id="contactImage" class="square-img" src="~/img/DefaultContactImage.png">
                    </div>
                    <div>
                        <input asp-for="ImageFile" class="form-control" accept=".png,.jpg,.jpeg,.gif" onchange="document.getElementById('contactImage').src= window.URL.createObjectURL(this.files[0])" />
                        <span asp-validation-for="ImageFile" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-12 col-lg-8">
                    <div class="row">
                        <div class="col-12 col-lg-6">
                            <label asp-for="FirstName" class="control-label"></label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="col-12 col-lg-6">
                            <label asp-for="LastName" class="control-label"></label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                        <div class="col-12 col-lg-6 mt-2">
                            <label asp-for="Email" class="control-label"></label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="col-12 col-lg-6 mt-2">
                            <label asp-for="PhoneNumber" class="control-label"></label>
                            <input asp-for="PhoneNumber" class="form-control" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="col-12 mt-2">
                            <label asp-for="Address1" class="control-label"></label>
                            <input asp-for="Address1" class="form-control" />
                            <span asp-validation-for="Address1" class="text-danger"></span>
                        </div>
                        <div class="col-12 mt-2">
                            <label asp-for="Address2" class="control-label"></label>
                            <input asp-for="Address2" class="form-control" />
                            <span asp-validation-for="Address2" class="text-danger"></span>
                        </div>
                        <div class="col-12 col-lg-6 mt-2">
                            <label asp-for="City" class="control-label"></label>
                            <input asp-for="City" class="form-control" />
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="col-12 col-lg-4 mt-2">
                            <label asp-for="State" class="control-label"></label>
                            <select asp-for="State" class="form-select" asp-items="ViewBag.StatesList">
                                <option></option>
                            </select>
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>
                        <div class="col-12 col-lg-2 mt-2">
                            <label asp-for="ZipCode" class="control-label"></label>
                            <input asp-for="ZipCode" class="form-control" />
                            <span asp-validation-for="ZipCode" class="text-danger"></span>
                        </div>
                        <div class="col-12 col-lg-6 mt-3">
                            <label asp-for="Categories" class="control-label"></label>
                            <select class="form-control" asp-items="@ViewBag.CategoryList" name="Selected" multiple></select>
                        </div>
                        <div class="col-12 col-lg-6 mt-3">
                            <label asp-for="BirthDate" class="control-label"></label>
                            <input asp-for="BirthDate" class="form-control" />
                            <span asp-validation-for="BirthDate" class="text-danger"></span>
                        </div>
                        <div class="col-12 d-flex justify-content-end mt-2">
                            <button type="submit" class="btn btn-lg btn-primary rounded-pill">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Contacts/Delete.cshtml
@model ContactPro.Models.Contact
@using ContactPro.Services.Interfaces;




@inject IImageService _ImageService
@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="col-12 col-md-8 offset-md-2">
        <h2>Are you sure?</h2>
        <p class="text-lead text-muted">This contact will be permanently deleted.</p>
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4 square-img-container">
                    <img src="@_ImageService.ConvertByteArrayToFile(Model.ImageDate!, Model.ImageType!)" class="square-img rounded-start" alt="...">
                </div>
                <div class="col-md-5">
                    <div class="card-body">
                        <h5 class="card-title">@Model.FullName</h5>
                        <address class="card-text">
                            @Model.Address1<br />
                            @if (!string.IsNullOrEmpty(Model.Address2))
                            {
                                @Model.Address2
                                <br />
                            }
                            @Model.City, @Model.State @Model.ZipCode
                        </address>
                        <div class="card-text">
                            <span class="fw-bold me-2">Phone:</span>@Model.PhoneNumber
                        </div>
                        <div class="card-text">
                            <span class="fw-bold me-2">Email:</span>@Model.Email
                        </div>
                        <div>
                            @foreach (Category category in Model.Categories)
                            {
                                <span class="badge rounded-pill border border-1 text-dark fw-normal">@category.Name</span>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <form class="d-flex justify-content-between" asp-action="Delete" asp-route-id="@Model.Id">
            <input hidden asp-for="Id" />
            <a asp-action="Index" asp-controller="Contacts" class="btn btn-outline-secondary rounded-pill btnLink">Cancel</a>
            <button type="submit" class="btn btn-danger rounded-pill btnLink">Delete</button>
        </form>
    </div>
</div>

Views/Contacts/Details.cshtml
@model ContactPro.Models.Contact

@using ContactPro.Services.Interfaces;



@inject IImageService _ImageService

@{
    ViewData["Title"] = "Details";
}

<h1>CONTACT DETAILS</h1>
<div class="p-3 border border-2 shadow-lg bg-light mb-5">
    <div class="row g-3 p-2">
        <div class="col-12 col-lg-4">
            <div class="square-img-container mb-3">
                <img id="contactImage" class="square-img" src="@_ImageService.ConvertByteArrayToFile(Model.ImageDate!, Model.ImageType!)" />
            </div>
        </div>
        <div class="col-12 col-lg-8">
            <div class="row">
                <div class="col-12 col-lg-6">
                    <label asp-for="FirstName" class="control-label"></label>
                    <span asp-for="FirstName" class="form-control">@Model.FirstName</span>
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>                <div class="col-12 col-lg-6">
                    <label asp-for="LastName" class="control-label"></label>
                    <span asp-for="LastName" class="form-control">@Model.LastName</span>
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>                <div class="col-12 col-lg-6 mt-2">
                    <label asp-for="Email" class="control-label"></label>
                    <span asp-for="Email" class="form-control">@Model.Email</span>
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="col-12 col-lg-6 mt-2">
                    <label asp-for="PhoneNumber" class="control-label"></label>
                    <span asp-for="PhoneNumber" class="form-control">@Model.PhoneNumber</span>
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="col-12 mt-2">
                    <label asp-for="Address1" class="control-label"></label>
                    <span asp-for="Address1" class="form-control">@Model.Address1</span>
                    <span asp-validation-for="Address1" class="text-danger"></span>
                </div>
                <div class="col-12 mt-2">
                    <label asp-for="Address2" class="control-label"></label>
                    <span asp-for="Address2" class="form-control">@Model.Address2 &nbsp;</span>
                    <span asp-validation-for="Address2" class="text-danger"></span>
                </div>
                <div class="col-12 col-lg-6 mt-2">
                    <label asp-for="City" class="control-label"></label>
                    <span asp-for="City" class="form-control">@Model.City</span>
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="col-12 col-lg-4 mt-2">
                    <label asp-for="State" class="control-label"></label>
                    <span asp-for="State" class="form-control">@Model.State</span>
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>
                <div class="col-12 col-lg-2 mt-2">
                    <label asp-for="ZipCode" class="control-label"></label>
                    <span asp-for="ZipCode" class="form-control">@Model.ZipCode</span>
                    <span asp-validation-for="ZipCode" class="text-danger"></span>
                </div>
                @*                    <div class="col-12 col-lg-6 mt-3">
                <label asp-for="Contact!.Categories" class="control-label"></label>
                <select class="form-control" asp-items="@Model.CategoryList" asp-for="SelectedCategories" multiple></select>
                </div>*@
                <div class="col-12 col-lg-6 mt-3">
                    <label asp-for="BirthDate" class="control-label"></label>
                    <span asp-for="BirthDate" class="form-control">@Model.BirthDate?.ToString("MM/dd/yyyy") &nbsp</span>
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>
                <div class="col-12 d-flex justify-content-end mt-2">
                    <a asp-action="Index" class="mx-2 btn btn-lg btn-secondary rounded-pill btnlinks">Back</a>
                    <a asp-action="Edit" asp-route-id="@Model?.Id" class="mx-2 btn btn-lg btn-warning rounded-pill btnlinks">Edit</a>
                    <a asp-action="Delete" class="mx-2 btn btn-lg btn-danger rounded-pill btnlinks">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Contacts/EmailContact.cshtml
@model ContactPro.Models.ViewModels.EmailContactViewModel


<h1 class="mt-5">Email Contact: @Model.EmailData!.FirstName @Model.EmailData.LastName</h1>
<div class="p-2">
    <form asp-action="EmailContact" asp-controller="Contacts" method="post">
        <input type="hidden" asp-for="@Model.EmailData.GroupName" />
        <div class="row row-cols-1 row-cols-md-2 g-3 mb-3">
            <div class="col col-md-12">
                <label asp-for="@Model.EmailData.EmailAddress" class="form-label">To:</label>
                <textarea type="email" readonly class="form-control" asp-for="@Model.EmailData.EmailAddress" rows="3"></textarea>
            </div>
        </div>
        <div class="row row-cols-1 g-3">
            <div class="col">
                <label asp-for="@Model.EmailData.EmailSubject" class="form-label">Subject:</label>
                <input type="text" class="form-control" asp-for="@Model.EmailData.EmailSubject" />
            </div>
            <div class="col">
                <label asp-for="@Model.EmailData.EmailBody" class="form-label">Message:</label>
                <textarea class="form-control" rows=10 asp-for="@Model.EmailData.EmailBody" required></textarea>
            </div>
            <div class="col text-end">
                <button class="btn btn-primary rounded-pill btnlinks" type="submit">Send</button>
            </div>
        </div>
    </form>
</div>

Views/Contacts/Index.cshtml
@model IEnumerable<ContactPro.Models.Contact>
@using ContactPro.Services.Interfaces;



    @inject IImageService _ImageService

@{
    ViewData["Title"] = "Index";
}

<h1>My Contacts</h1>
<div class="row">
    <div class="col-12 text-end mb-2">
        <a class="btn btn-primary rounded-pill" asp-action="Create">Create New</a>
    </div>
</div>
<div class="row g-2">
    <div class="col-12 col-md-4 sideNav">
        <form asp-action="SearchContacts" asp-controller="Contacts" method="post">
            <div class="input-group">
                <input class="form-control" type="search" name="searchString"
                       placeholder="Search Term" />
                <input type="submit" class="btn btn-outline-primary" value="Search" />
            </div>
        </form>
        <form asp-action="Index" asp-controller="Contacts" method="post">
            <div class="mt-5">
                <label class="form-label fw-bold">CATEGORY FILTER</label>
                <select name="categoryId" asp-items="@ViewBag.CategoryId" class="form-control"
                        onchange="this.form.submit()" onfocus="this.selectedIndex=-1;this.blur();">
                    <option>All Contacts</option>
                </select>
            </div>
        </form>
    </div>
    <div class="col-12 col-md-8">
        <div class="row row-cols-1 g-3">
            @foreach (var contact in Model)
            {
                <div class="col">
                    <div class="card mb-3">
                        <div class="row g-0">
                            <div class="col-md-4 square-img-container">
                                <img src='@_ImageService.ConvertByteArrayToFile(contact.ImageDate!,contact.ImageType!)' class="square-img rounded-start">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">@Html.DisplayFor(modelItem => contact.FullName)</h5>
                                    <address class="card-text">
                                        @Html.DisplayFor(modelItem => contact.Address1)<br>
                                        @Html.DisplayFor(modelItem => contact.Address2)<br>
                                        @Html.DisplayFor(modelItem => contact.City), @Html.DisplayFor(modelItem => contact.State) @Html.DisplayFor(modelItem => contact.ZipCode)
                                    </address>
                                    <div class="card-text">
                                        <span class="fw-bold me-2">Phone:</span>@Html.DisplayFor(modelItem => contact.PhoneNumber)
                                    </div>
                                    <div class="card-text">
                                        <span class="fw-bold me-2">Email:</span>@Html.DisplayFor(modelItem => contact.Email)
                                    </div>
                                    <div class="fs-4">
                                        <a class="me-3 editIcons" asp-action="Edit" asp-route-id="@contact.Id"><i class="bi bi-pencil-fill "></i></a>
                                        <a class="me-3 editIcons" asp-action="EmailContact" asp-route-id="@contact.Id"><i class="bi bi-envelope-fill "></i></a>
                                        <a class="me-3 editIcons" asp-action="Delete" asp-route-id="@contact.Id"><i class="bi bi-trash-fill text-danger "></i></a>
                                    </div>
                                    <div>
                                        @foreach (Category category in contact.Categories)
                                        {
                                            <span class="badge rounded-pill border border-1 text-dark fw-normal">@category.Name</span>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section scripts{
    <!--Sweet Alerts-->
    <script>
        let message = '@(ViewBag.SwalMessage)';
        if (!message.includes("Error") && message != '') {
            Swal.fire({
                backdrop: false,
                icon: 'success',
                title: message,
                showConfirmButton: true
            })
        } else if (message.includes("Error")) {
            Swal.fire({
                backdrop: false,
                icon: 'error',
                title: 'Oops...',
                text: message
            })
        }
    </script>
    }